### ISSUE TITLE
My Work: Default view

### ISSUE THREAD

**Issue by bluedoorsoftware** [bluedoorsoftware/CWCOnlineKendo#11]
please show empty grid, not no grid

![image](https://cloud.githubusercontent.com/assets/1998630/9022250/7ffb58ec-3866-11e5-8197-1cc2c42031c0.png)

**Comment by frabbibd** [comment]
Done, Please check.

**Comment by bluedoorsoftware** [comment]
Not fixed
=======
grid is not empty

**Comment by frabbibd** [comment]
Done. Please check

**Comment by bluedoorsoftware** [comment]
Verified. Closing
