### ISSUE TITLE
SMS

### ISSUE THREAD

**Issue by bluedoorsoftware** [bluedoorsoftware/CWCOnlineKendo#15]
Remove all toolbars in this dialog as formatted text is not possible by SMS
![image](https://cloud.githubusercontent.com/assets/1998630/9022312/e7080a6a-3868-11e5-8bc4-e612a31e5678.png)

**Comment by frabbibd** [comment]
Done, please check.

**Comment by bluedoorsoftware** [comment]
Verified. Closing
