### ISSUE TITLE
Main Page

### ISSUE THREAD

**Issue by bluedoorsoftware** [bluedoorsoftware/CWCOnlineKendo#16]
Insert some lorum ipsor text here (under the Welcome, Chris). I need to add some introductory text. Add a couple of paragraphs as placeholder

![image](https://cloud.githubusercontent.com/assets/1998630/9022327/9032b40a-3869-11e5-85cb-68eeb40914a9.png)

**Comment by frabbibd** [comment]
Done, please check.

**Comment by bluedoorsoftware** [comment]
Verified. Closing
