### ISSUE TITLE
Demo Tips

### ISSUE THREAD

**Issue by bluedoorsoftware** [bluedoorsoftware/CWCOnlineKendo#2]
Change demo tips so that they do not overlap, and also remove the X button from the tip:
![image](https://cloud.githubusercontent.com/assets/1998630/9022212/e1e9a2b8-3864-11e5-999f-11be0cfeed94.png)

**Comment by frabbibd** [comment]
Overlapped removed but X is not removed. Will be removed by tomorrow.

**Comment by frabbibd** [comment]
done. Please check

**Comment by bluedoorsoftware** [comment]
Closing,.
