### ISSUE TITLE
Welcome page: responsive issue

### ISSUE THREAD

**Issue by bluedoorsoftware** [bluedoorsoftware/CWCOnlineKendo#20]
Tiles are not resizing correctly (look at bottom of the window):

![image](https://cloud.githubusercontent.com/assets/1998630/9022378/eb996d9c-386a-11e5-9b58-2ad2dd2930ee.png)

**Comment by frabbibd** [comment]
Please check.

**Comment by bluedoorsoftware** [comment]
verified. Closing
