### ISSUE TITLE
Forgotten password ui layout is not good

### ISSUE THREAD

**Issue by bluedoorsoftware** [bluedoorsoftware/CWCOnlineKendo#21]
![image](https://cloud.githubusercontent.com/assets/1998630/9022409/19230042-386c-11e5-9066-1e6ee67410ff.png)

**Comment by frabbibd** [comment]
Please check.

**Comment by bluedoorsoftware** [comment]
Not fixed
=======
![image](https://cloud.githubusercontent.com/assets/1998630/9045929/2a4d9936-3a1f-11e5-9fcb-17d0519a6574.png)

**Comment by frabbibd** [comment]
Done. Please check

**Comment by bluedoorsoftware** [comment]
verified. closing
