### ISSUE TITLE
Login Validation

### ISSUE THREAD

**Issue by bluedoorsoftware** [bluedoorsoftware/CWCOnlineKendo#23]
Whatever the validation error, replace with this single message:

![image](https://cloud.githubusercontent.com/assets/1998630/9022521/c90bbcb2-386f-11e5-81f4-9118a63a8797.png)

**Comment by frabbibd** [comment]
Please check.

**Comment by bluedoorsoftware** [comment]
Not fixed 1
========
This is when password is not correct:
![image](https://cloud.githubusercontent.com/assets/1998630/9045962/6467da64-3a1f-11e5-91b3-92e69145115d.png)


Not fixed 2
=========
If I click Log In after entering the wrong password, I am logged in!!!!

Not fixed 3
=========
![image](https://cloud.githubusercontent.com/assets/1998630/9045989/866b6536-3a1f-11e5-8c33-b19610b3f87e.png)

**Comment by frabbibd** [comment]
Done. Please check

**Comment by frabbibd** [comment]
Done. Please check

**Comment by bluedoorsoftware** [comment]
Fixed, but new issue. When enter bad user name and bad password, on click of Log In button, password field is cleared. The requirement is that the password field should not be cleared.

**Comment by frabbibd** [comment]
Now even wrong username and password given and after calling wcf service error message is shown and keep the username and password in the text boxes. Please check.

**Comment by bluedoorsoftware** [comment]
Yes, correct now.

One minor text change in error message: "Unknown" not "unknown" (captial U) please

**Comment by frabbibd** [comment]
This is done, please check.

**Comment by bluedoorsoftware** [comment]
Fixed. Closing
