### ISSUE TITLE
Tile vector images

### ISSUE THREAD

**Issue by bluedoorsoftware** [bluedoorsoftware/CWCOnlineKendo#25]
I have sent you a link to a lightbox on Shutterstock. Please use these vectors on the Main Page

**Comment by bluedoorsoftware** [comment]
..once we are all happy I will buy the image. For now use the low resolution images from the lightbox

**Comment by bluedoorsoftware** [comment]
Image ID: 193806341 > Referrals
Image ID: 180559742 > Scheduler
Image ID: 273700574 > Library
Image ID: 233171779 > Reports
Image ID: 200640083 > SMS
Image ID: 141441646 > Maps
Image ID: 292931828 > My Work

**Comment by frabbibd** [comment]
Images are inserted from shutter stock. Please check.

**Comment by bluedoorsoftware** [comment]
Verified. Closing
