### ISSUE TITLE
Searching for Referrals

### ISSUE THREAD

**Issue by bluedoorsoftware** [bluedoorsoftware/CWCOnlineKendo#3]
When searching like this:
![image](https://cloud.githubusercontent.com/assets/1998630/9022216/046f7902-3865-11e5-8b3c-5c16e3269244.png)

The grid should highlight the matched text. Here is example from SL project:
![image](https://cloud.githubusercontent.com/assets/1998630/9022223/22edd13a-3865-11e5-9d4b-d05c8a253118.png)

**Comment by frabbibd** [comment]
Done. Please check

**Comment by bluedoorsoftware** [comment]
Verified. Closing
