### ISSUE TITLE
Main Page template

### ISSUE THREAD

**Issue by bluedoorsoftware** [bluedoorsoftware/CWCOnlineKendo#30]
I want a header adding like the footer and the home icon, Welcome message, and Sign Out link placing inside it. The header/footer should mirror each other:

![image](https://cloud.githubusercontent.com/assets/1998630/9046120/68b55802-3a20-11e5-8844-37cc44262347.png)

**Comment by frabbibd** [comment]
Done. Please check

**Comment by bluedoorsoftware** [comment]
not fixed
=======
Easier if we discuss
