### ISSUE TITLE
Log in : Tab Sequence

### ISSUE THREAD

**Issue by bluedoorsoftware** [bluedoorsoftware/CWCOnlineKendo#31]
Change to this order of tab:
![image](https://cloud.githubusercontent.com/assets/1998630/9067810/a427e3f2-3ad7-11e5-98bd-6c2f0b80788e.png)

**Comment by frabbibd** [comment]
Done, please check.

**Comment by bluedoorsoftware** [comment]
Tab order correct.

Please set it so Username field has focus when page is loaded, so user can just start typing

**Comment by frabbibd** [comment]
Done, please check.

**Comment by bluedoorsoftware** [comment]
Verified. Closing
