### ISSUE TITLE
Referrals: tabs on right

### ISSUE THREAD

**Issue by bluedoorsoftware** [bluedoorsoftware/CWCOnlineKendo#4]
Resize so aligned to bottom and fills area:
![image](https://cloud.githubusercontent.com/assets/1998630/9022226/50ce5dea-3865-11e5-9c72-937843ea7bc4.png)

**Comment by frabbibd** [comment]
Height is increased.

**Comment by bluedoorsoftware** [comment]
Verified. Closing
